// <auto-generated />
namespace Market.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kategorikar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kategorikar));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081031489_kategorikar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
